# Generated by Django 5.2.17 on 2026-08-15 02:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0001_initial'),
        ('posting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('useful_life_years', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('disposal_date', models.DateField(db_index=True)),
                ('proceeds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('gain', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(default='draft', max_length=16)),
            ],
            options={
                'ordering': ['-disposal_date'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('is_still_in_use', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['asset', 'period_start'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('asset_no', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('acquisition_date', models.DateField(db_index=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('funding_source', models.CharField(default='cash', max_length=16)),
                ('financed_loan_reference', models.CharField(blank=True, max_length=64)),
                ('acquisition_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fully_depreciated', 'Fully Depreciated (still in use)'), ('disposed', 'Disposed')], db_index=True, default='active', max_length=24)),
                ('accumulated_dep_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_accum_dep', to='foundation.account')),
                ('acquisition_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_acquired', to='posting.journalentry')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_asset', to='foundation.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('depreciation_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_dep_exp', to='foundation.account')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquisition_date', 'asset_no'],
            },
        ),
    ]
