# Generated by Django 5.2.17 on 2026-08-15 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('fleet', '0001_initial'),
        ('foundation', '0001_initial'),
        ('posting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='accumulated_dep_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories_accum', to='foundation.account'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='asset_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories_asset', to='foundation.account'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='depreciation_expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories_dep_exp', to='foundation.account'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_categories', to='foundation.segment'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposal', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_disposals', to='posting.journalentry'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depreciationschedule',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_schedule', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='depreciationschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depreciationschedule',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_rows', to='posting.journalentry'),
        ),
        migrations.AddField(
            model_name='depreciationschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='depreciationschedule',
            unique_together={('asset', 'period_start')},
        ),
    ]
