# Generated by Django 5.2.17 on 2026-09-07 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('posting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reversal_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='posted', max_length=16)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_reversals', to='posting.journalentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reversal_date'],
            },
        ),
    ]
