# Generated by Django 5.2.17 on 2026-09-28 03:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0017_alter_actionlog_doc_type'),
        ('assets', '0003_assetreversal'),
        ('foundation', '0013_userprofile_avatar_userprofile_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('approved', 'Approved (ready to post)'), ('rejected', 'Rejected'), ('posted', 'Posted to GL')], db_index=True, default='posted', max_length=16),
        ),
        migrations.AddField(
            model_name='asset',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='ap.purchaseorder'),
        ),
        migrations.AddField(
            model_name='asset',
            name='reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='asset',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='revision_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='ap.supplier'),
        ),
        migrations.AddField(
            model_name='asset',
            name='useful_life_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('side', models.CharField(choices=[('dr', 'Dr'), ('cr', 'Cr')], default='dr', max_length=2)),
                ('cost_center', models.CharField(blank=True, max_length=64, verbose_name='Cost Center/Ref')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_lines', to='foundation.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='assets.asset')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_lines', to='foundation.segment')),
            ],
            options={
                'ordering': ['asset', 'line_no'],
                'unique_together': {('asset', 'line_no')},
            },
        ),
    ]
