# Generated by Django 5.2.17 on 2026-08-15 02:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthEndClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('steps', models.JSONField(default=dict, help_text='{"accruals": "pending", "recon": "pending", "close": "pending", "appropriations": "pending"}')),
                ('status', models.CharField(default='open', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_end_closes', to='foundation.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='month_end_close', to='foundation.fiscalperiod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fiscal_period__period_no'],
            },
        ),
        migrations.CreateModel(
            name='StatementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('statement_type', models.CharField(choices=[('tb', 'Trial Balance'), ('is', 'Income Statement'), ('sfp', 'Statement of Financial Position'), ('cos', 'Statement of Cost of Sales'), ('te', 'Statement of Total Expenses'), ('soce', 'Statement of Changes in Equity'), ('cf', 'Cash Flow Statement')], max_length=8, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['statement_type'],
            },
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('statement_type', models.CharField(choices=[('tb', 'Trial Balance'), ('is', 'Income Statement'), ('sfp', 'Statement of Financial Position'), ('cos', 'Statement of Cost of Sales'), ('te', 'Statement of Total Expenses'), ('soce', 'Statement of Changes in Equity'), ('cf', 'Cash Flow Statement')], max_length=8)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('data', models.JSONField(default=list)),
                ('identity_ok', models.BooleanField(default=True)),
                ('identity_note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='foundation.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', 'statement_type', 'segment'],
                'indexes': [models.Index(fields=['statement_type', 'company', 'period_start', 'period_end'], name='reporting_f_stateme_3cdeac_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatementLineDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('account', 'Sum of accounts by code/prefix'), ('sum', 'Sum of child lines'), ('difference', 'Difference of two lines'), ('ratio', 'Ratio of two lines (percent)'), ('percent', 'Fixed percent of the base line'), ('quantity', 'Quantity (liters)'), ('input', 'Value injected by the caller')], max_length=16)),
                ('balance_basis', models.CharField(choices=[('activity', 'Period activity'), ('opening', 'Opening balance (before period)'), ('ending', 'Ending balance (through period end)')], default='activity', max_length=16)),
                ('account_codes', models.JSONField(default=list)),
                ('account_prefixes', models.JSONField(default=list)),
                ('sign', models.DecimalField(decimal_places=0, default=Decimal('1'), max_digits=2)),
                ('is_subtotal', models.BooleanField(default=False)),
                ('is_section', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('left_ref', models.CharField(blank=True, max_length=64)),
                ('right_ref', models.CharField(blank=True, max_length=64)),
                ('weight', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='reporting.statementlinedef')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='reporting.statementtemplate')),
            ],
            options={
                'ordering': ['template', 'line_no'],
                'unique_together': {('template', 'line_no')},
            },
        ),
    ]
