# Generated by Django 5.2.6 on 2026-09-03 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthendclose',
            name='appropriation_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posting.journalentry'),
        ),
        migrations.AddField(
            model_name='monthendclose',
            name='expense_close_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posting.journalentry'),
        ),
        migrations.AddField(
            model_name='monthendclose',
            name='revenue_close_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posting.journalentry'),
        ),
    ]
