# Generated by Django 5.2.17 on 2026-08-14 07:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('entry_no', models.CharField(max_length=32, unique=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('approved', 'Approved (posting eligible)'), ('posted', 'Posted'), ('reversed', 'Reversed (matched by reversing entry)'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('description', models.CharField(max_length=500)),
                ('source_doc_type', models.CharField(blank=True, max_length=16)),
                ('source_doc_no', models.CharField(blank=True, db_index=True, max_length=32)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('reversal_token', models.CharField(blank=True, db_index=True, max_length=40)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='foundation.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='foundation.fiscalperiod')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='je_lines', to='foundation.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='posting.journalentry')),
            ],
            options={
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_lines', to='foundation.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_lines', to='foundation.company')),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.fiscalperiod')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_lines', to='foundation.segment')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_lines', to='posting.journalentry')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gl', to='posting.journalentryline')),
            ],
            options={
                'ordering': ['transaction_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PostingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('event', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PostingRuleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('side', models.CharField(max_length=8)),
                ('account_code', models.CharField(max_length=10)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('share', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5)),
                ('use_balance', models.BooleanField(default=False, verbose_name='take remainder')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='posting.postingrule')),
            ],
            options={
                'ordering': ['rule', 'line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'transaction_date'], name='posting_jou_company_abe517_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status', 'source_doc_type'], name='posting_jou_status_a8a943_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentryline',
            unique_together={('entry', 'line_no')},
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['account', 'transaction_date'], name='posting_gen_account_e44e89_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['company', 'segment', 'transaction_date'], name='posting_gen_company_b89f21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postingruleline',
            unique_together={('rule', 'line_no')},
        ),
    ]
