# Generated by Django 5.2.6 on 2026-09-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_journalentry_approved_at_journalentry_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='po',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='ref_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
