# Generated by Django 5.2.17 on 2026-09-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_journalentry_po_journalentry_ref_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='cost_center',
            field=models.CharField(blank=True, max_length=64, verbose_name='Cost center'),
        ),
    ]
