# Generated by Django 5.2.17 on 2026-09-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_journalentryline_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.TextField(),
        ),
    ]
