# Generated by Django 5.2.6 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="answer",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]