# Generated by Django 5.2.6 on 2026-09-03 00:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ap', '0002_rfp_manual_sides'),
        ('ar', '0002_alter_cashshortexcess_segment'),
        ('foundation', '0007_alter_segmentaccountmap_role'),
        ('posting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTaxProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('filing_period', models.CharField(max_length=16)),
                ('taxable_income', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_tax_provisions', to='posting.journalentry')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_tax_provisions', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-filing_period'],
            },
        ),
        migrations.CreateModel(
            name='TaxCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('form', models.CharField(choices=[('2307', '2307 — Certificate of Creditable Tax Withheld at Source'), ('2306', '2306 — Certificate of Final Tax Withheld at Source'), ('2316', '2316 — Certificate of Compensation Payment/Tax Withheld'), ('2550Q', '2550Q — Monthly Quarterly VAT Return'), ('2551Q', '2551Q — Percentage Tax Return'), ('1702Q', '1702Q — Quarterly Income Tax Return'), ('1702', '1702 — Annual Income Tax Return')], max_length=8)),
                ('filing_period', models.CharField(max_length=16)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('not_due', 'Not due'), ('due', 'Due'), ('filed', 'Filed'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='not_due', max_length=16)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_calendar', to='foundation.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'form'],
                'unique_together': {('form', 'company', 'filing_period')},
            },
        ),
        migrations.CreateModel(
            name='VATComputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('vat_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1200'), max_digits=5)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('output_vat', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vat_computation', to='ar.arinvoice')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vat_computations', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['invoice__transaction_date', 'invoice__invoice_no'],
            },
        ),
        migrations.CreateModel(
            name='WithholdingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cert_type', models.CharField(choices=[('2307', '2307 — Expanded (creditable) withholding'), ('2306', '2306 — Final withholding')], max_length=8)),
                ('tin', models.CharField(blank=True, max_length=32, verbose_name='TIN')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cv_number', models.CharField(blank=True, max_length=32)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='tax.taxcalendar')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wht_certificates', to='ap.supplier')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wht_certificates', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cv_number', 'segment__code'],
            },
        ),
    ]
