# Generated by Django 5.2.17 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="classification",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="account",
            name="category",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="account",
            name="sub_accounts",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="account",
            name="major_accounts",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
