# Generated by Django 5.2.6 on 2026-09-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_approval_roles_three_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cash_cycle',
            field=models.CharField(choices=[('weekly', 'Weekly (Tue->Mon)'), ('monthly', 'Monthly (calendar)')], default='weekly', max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='cycle_end_weekday',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='cycle_start_weekday',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
