# Generated by Django 5.2.6 on 2026-09-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_segmentaccountmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentaccountmap',
            name='role',
            field=models.CharField(choices=[('ap', 'Accounts payable (CV Dr)'), ('ap_wht', 'Withholding tax expanded (CV Cr)'), ('cash', 'Cash default (proceeds / funding)'), ('loans', 'Loans payable (financed acquisition)'), ('disposal_gain', 'Gain on asset disposal'), ('disposal_loss', 'Loss on asset disposal'), ('income_tax', 'Income tax payable (provision Cr)'), ('vat_output', 'Output VAT payable (SI extraction Cr)')], max_length=24),
        ),
    ]
