# Generated by Django 5.2.17 on 2026-09-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0008_alter_segmentaccountmap_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('contra_asset', 'Contra-Asset'), ('contra_liability', 'Contra-Liability'), ('contra_revenue', 'Contra-Revenue'), ('contra_equity', 'Contra-Equity'), ('drawing', 'Drawing')], max_length=24),
        ),
    ]
