# Generated by Django 5.2.17 on 2026-09-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0010_costcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='behavior',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='controllability',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='traceability',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
