# Generated by Django 5.2.17 on 2026-09-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0011_account_behavior_account_controllability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='screen_access',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
