# Generated by Django 5.2.17 on 2026-09-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0012_userprofile_screen_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(blank=True, choices=[('teal', 'Teal (default)'), ('ocean', 'Ocean'), ('indigo', 'Indigo'), ('plum', 'Plum'), ('sunset', 'Sunset'), ('forest', 'Forest'), ('blossom', 'Blossom'), ('crimson', 'Crimson')], default='teal', max_length=16),
        ),
    ]
