# Generated by Django 5.2.17 on 2026-09-21 02:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ap', '0017_alter_actionlog_doc_type'),
        ('ar', '0006_alter_deposit_options_and_more'),
        ('foundation', '0011_account_behavior_account_controllability_and_more'),
        ('posting', '0007_reversalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('billing_no', models.CharField(max_length=32, unique=True)),
                ('billing_type', models.CharField(choices=[('stpc', 'Intercompany Billing - STPC'), ('third_party', 'Third-Party Billing')], db_index=True, default='third_party', max_length=16)),
                ('billing_date', models.DateField(db_index=True)),
                ('party_name', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('particulars', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('approved', 'Approved (ready to post)'), ('posted', 'Posted to GL')], db_index=True, default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('revision_count', models.PositiveSmallIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_documents', to='foundation.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_documents', to='ar.customer')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_documents', to='posting.journalentry')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rfp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_documents', to='ap.rfpdocument')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_documents', to='foundation.segment')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_documents', to='ap.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-billing_date', '-billing_no'],
            },
        ),
        migrations.CreateModel(
            name='BillingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('side', models.CharField(choices=[('dr', 'Dr'), ('cr', 'Cr')], default='dr', max_length=2)),
                ('cost_center', models.CharField(blank=True, max_length=64, verbose_name='Cost Center/Ref')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_lines', to='foundation.account')),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.billingdocument')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_lines', to='foundation.segment')),
            ],
            options={
                'ordering': ['billing', 'line_no'],
                'unique_together': {('billing', 'line_no')},
            },
        ),
    ]
