# Generated by Django 5.2.17 on 2026-10-06 03:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_unbilled_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdocument',
            name='supplier',
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='customer_id_display',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='downpayment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='downpayment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='downpayment_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='downpayment_ref',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='due_text',
            field=models.CharField(blank=True, default='IMMEDIATELY', max_length=32),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='remaining_note',
            field=models.CharField(blank=True, default='REMAINING BALANCE TO BE PAID AFTER THE ONLINE APPROVAL OF DOE', max_length=255),
        ),
        migrations.AddField(
            model_name='billingdocument',
            name='statement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BillingInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.PositiveIntegerField(default=1)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('billing_ref', models.CharField(blank=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='billing.billingdocument')),
            ],
            options={
                'ordering': ['billing', 'order_no'],
                'unique_together': {('billing', 'order_no')},
            },
        ),
    ]
