# Generated by Django 5.2.6 on 2026-09-03 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0007_alter_segmentaccountmap_role'),
        ('posting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollFeed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_reference', models.CharField(max_length=64, unique=True)),
                ('schema_version', models.CharField(default='v1', max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('entity', models.CharField(max_length=8)),
                ('cost_center', models.CharField(blank=True, max_length=8)),
                ('net_pay_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('er_share_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remittance_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('reviewed', 'Reviewed (ready to post)'), ('posted', 'Posted'), ('rejected', 'Rejected')], default='uploaded', max_length=16)),
                ('archived_file', models.FileField(blank=True, upload_to='payroll_feeds/')),
                ('validation_error', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_feeds', to='foundation.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_feeds', to='posting.journalentry')),
                ('review_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_feeds', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-batch_reference'],
            },
        ),
        migrations.CreateModel(
            name='PayrollFeedLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('cost_center', models.CharField(blank=True, max_length=8)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollfeed')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='foundation.account')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='foundation.segment')),
            ],
            options={
                'ordering': ['feed', 'line_no'],
            },
        ),
    ]
