# Generated by Django 5.2.17 on 2026-08-14 08:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0001_initial'),
        ('posting', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('fuel', 'Fuel'), ('equipment', 'Equipment'), ('ops', 'Operations')], default='fuel', max_length=16)),
                ('pricing_tier', models.CharField(choices=[('regular', 'Regular'), ('patron', 'Patron'), ('volume', 'Volume')], default='regular', max_length=16)),
                ('tin', models.CharField(blank=True, max_length=32, verbose_name='TIN')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_no', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ARInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('invoice_no', models.CharField(max_length=32, unique=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('is_paid_on_delivery', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(default='open', max_length=16)),
                ('booked_on_payment', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_invoices', to='posting.journalentry')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_invoices', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='ar.customer')),
            ],
            options={
                'ordering': ['-transaction_date', '-invoice_no'],
            },
        ),
        migrations.CreateModel(
            name='AcknowledgmentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('receipt_no', models.CharField(max_length=32, unique=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('gcash', 'GCash'), ('others', 'Others')], default='cash', max_length=8)),
                ('check_no', models.CharField(blank=True, max_length=32)),
                ('cash_account', models.ForeignKey(limit_choices_to={'code__startswith': '100'}, on_delete=django.db.models.deletion.PROTECT, related_name='ar_receipts', to='foundation.account')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_receipts', to='posting.journalentry')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_receipts', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('applied_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='ar.arinvoice')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='ar.customer')),
            ],
            options={
                'ordering': ['-transaction_date', '-receipt_no'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('bank_account', models.ForeignKey(limit_choices_to={'code__startswith': '100'}, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='foundation.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deposited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='ARInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('product_code', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ar.arinvoice')),
            ],
            options={
                'ordering': ['invoice', 'line_no'],
                'unique_together': {('invoice', 'line_no')},
            },
        ),
        migrations.CreateModel(
            name='CashShortExcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cycle_start', models.DateField(db_index=True)),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=18)),
                ('actual_cash', models.DecimalField(decimal_places=2, max_digits=18)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cause', models.TextField(blank=True)),
                ('status', models.CharField(default='open', max_length=16)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.approvalrequest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_short_excesses', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cycle_start'],
                'unique_together': {('cycle_start', 'segment')},
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product_code', models.CharField(max_length=32)),
                ('cycle_start', models.DateField(db_index=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tier', models.CharField(choices=[('regular', 'Regular'), ('patron', 'Patron'), ('volume', 'Volume')], default='regular', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_snapshots', to='ar.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['customer', 'cycle_start', 'product_code'],
                'unique_together': {('customer', 'product_code', 'cycle_start')},
            },
        ),
    ]
