# Generated by Django 5.2.17 on 2026-08-15 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0001_initial'),
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashshortexcess',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_cash_short_excesses', to='foundation.segment'),
        ),
    ]
