# Generated by Django 5.2.6 on 2026-09-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0002_alter_cashshortexcess_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Owner'),
        ),
    ]
