# Generated by Django 4.x — manual. Adds the optional Transaction No. reference.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0003_customer_owner_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="acknowledgmentreceipt",
            name="transaction_no",
            field=models.CharField(blank=True, max_length=64, verbose_name="Transaction No."),
        ),
    ]