# Generated by Django 5.2.17 on 2026-09-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0004_acknowledgmentreceipt_transaction_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgmentreceipt',
            name='ref_po_no',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ref. PO No.'),
        ),
    ]
