# Generated by Django 5.2.17 on 2026-09-18 03:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_receipts(apps, schema_editor):
    """Mark already-posted receipts and rebuild their distribution lines from
    the posted collection JE, so history is available in the new module."""
    AcknowledgmentReceipt = apps.get_model("ar", "AcknowledgmentReceipt")
    ReceiptLine = apps.get_model("ar", "AcknowledgmentReceiptLine")

    for receipt in AcknowledgmentReceipt.objects.select_related("journal_entry"):
        if receipt.journal_entry_id is None:
            continue
        receipt.status = "posted"
        receipt.save(update_fields=["status"])
        if receipt.lines.exists():
            continue
        for i, line in enumerate(receipt.journal_entry.lines.all().order_by("line_no"), start=1):
            ReceiptLine.objects.create(
                receipt=receipt,
                line_no=i,
                account_id=line.account_id,
                segment_id=line.segment_id or receipt.segment_id,
                cost_center=line.cost_center or "",
                description=line.description or "",
                debit=line.debit,
                credit=line.credit,
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0005_acknowledgmentreceipt_ref_po_no'),
        ('foundation', '0011_account_behavior_account_controllability_and_more'),
        ('posting', '0005_journalentryline_cost_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-transaction_date', '-id']},
        ),
        migrations.AddField(
            model_name='acknowledgmentreceipt',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgmentreceipt',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acknowledgmentreceipt',
            name='attachment',
            field=models.FileField(blank=True, upload_to='ar_attachments/'),
        ),
        migrations.AddField(
            model_name='acknowledgmentreceipt',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='ar.deposit'),
        ),
        migrations.AddField(
            model_name='acknowledgmentreceipt',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acknowledgmentreceipt',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acknowledgmentreceipt',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='acknowledgmentreceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('posted', 'Posted to GL')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='deposit',
            name='attachment',
            field=models.FileField(blank=True, upload_to='ar_deposits/'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='deposit_no',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ar_deposits', to='posting.journalentry'),
        ),
        migrations.AlterField(
            model_name='acknowledgmentreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AcknowledgmentReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('cost_center', models.CharField(blank=True, max_length=64, verbose_name='Cost center')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_receipt_lines', to='foundation.account')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ar.acknowledgmentreceipt')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_receipt_lines', to='foundation.segment')),
            ],
            options={
                'ordering': ['line_no'],
                'unique_together': {('receipt', 'line_no')},
            },
        ),
        migrations.RunPython(backfill_receipts, noop),
    ]
