# Generated by Django 5.2.6 on 2026-09-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0006_alter_deposit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='segment',
        ),
    ]
