# Generated by Django 5.2.6 on 2026-09-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0007_remove_customer_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='arinvoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.user'),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.user'),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
    ]