# Generated by Django 5.2.6 on 2026-10-02 00:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0009_customer_approval_status_customer_approved_at_and_more'),
        ('foundation', '0013_userprofile_avatar_userprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='bank_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'code__startswith': '100'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='foundation.account'),
        ),
        migrations.CreateModel(
            name='DepositLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('cost_center', models.CharField(blank=True, max_length=64, verbose_name='Cost center')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_lines', to='foundation.account')),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ar.deposit')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='foundation.segment')),
            ],
            options={
                'ordering': ['line_no'],
                'unique_together': {('deposit', 'line_no')},
            },
        ),
    ]
