# Generated by Django 5.2.17 on 2026-10-02 03:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0010_add_deposit_line'),
        ('foundation', '0013_userprofile_avatar_userprofile_theme'),
        ('posting', '0007_reversalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('invoice_no', models.CharField(max_length=32, unique=True)),
                ('delivery_receipt_no', models.CharField(blank=True, max_length=32, verbose_name='Delivery Receipt No.')),
                ('transaction_date', models.DateField(db_index=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for approval'), ('posted', 'Posted to GL')], db_index=True, default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_invoices', to='ar.customer')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='special_invoices', to='posting.journalentry')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_invoices', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-invoice_no'],
            },
        ),
        migrations.CreateModel(
            name='SpecialSalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('cost_center', models.CharField(blank=True, max_length=64, verbose_name='Cost center')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssi_lines', to='foundation.account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ar.specialsalesinvoice')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ssi_lines', to='foundation.segment')),
            ],
            options={
                'ordering': ['line_no'],
                'unique_together': {('invoice', 'line_no')},
            },
        ),
    ]
