# Generated by Django 5.2.17 on 2026-08-15 02:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCycleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('activity_type', models.CharField(choices=[('collection_dist', 'Collections from Distribution'), ('other_collection', 'Other Cash Collections'), ('borrowed', 'Funds Borrowed from other accounts'), ('supplier_payment', 'Payments to Supplier of Petroleum'), ('rfp_ap', 'RFP of Accounts Payable [incl loans]'), ('capex', 'Disbursement for CAPEX'), ('pcf_replen', 'Cash Withdrawn for PCF Replenishment'), ('interacct_transfer', 'Inter-account fund transfer'), ('other_payment', 'Other Cash payments'), ('loan_cleared', 'Checks Cleared for Loan / Fuel')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycle_activities', to='cash.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='cash.weeklycashcycle')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cycle', 'activity_type'],
                'unique_together': {('cycle', 'activity_type', 'bank_account')},
            },
        ),
    ]
