# Generated by Django 5.2.6 on 2026-08-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_cashcycleactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcfreplenishment',
            name='payee_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pcfreplenishment',
            name='reference',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
