# Generated by Django 5.2.6 on 2026-09-04 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_company_level_banks'),
        ('foundation', '0008_alter_segmentaccountmap_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='signatories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='custodian_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Custodian'),
        ),
        migrations.AlterField(
            model_name='pettycashfund',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcf_funds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycashfund',
            name='fund_code',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='pettycashfund',
            name='gl_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pcf_funds', to='foundation.account'),
        ),
    ]
