# Generated by Django 5.2.17 on 2026-09-05 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0005_bankaccount_account_number_bankaccount_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pcfreplenishment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Customer Name'),
        ),
        migrations.AddField(
            model_name='pcfreplenishment',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
