# Generated by Django 5.2.17 on 2026-09-07 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0006_suppliercontact'),
        ('cash', '0006_add_requested_by_to_pcfreplenishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcfreplenishment',
            name='conso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pcf_replenishments', to='ap.consobatch'),
        ),
        migrations.AddField(
            model_name='pcfreplenishment',
            name='conso_line_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
