# Generated by Django 5.2.17 on 2026-09-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0007_pcfreplenishment_conso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcfreplenishment',
            name='voucher_no',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
