# Generated by Django 5.2.17 on 2026-09-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0008_pcfreplenishment_voucher_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcfreplenishment',
            name='cost_center',
            field=models.CharField(blank=True, help_text='e.g. OS, GEN-FUEL – shown at top of the form and on prints.', max_length=32, verbose_name='Cost Centre'),
        ),
    ]
