# Generated by Django 5.2.17 on 2026-09-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0009_pcfreplenishment_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcfreplenishment',
            name='cost_center',
            field=models.CharField(blank=True, help_text='e.g. OS, GEN-FUEL – shown at top of the form and on prints.', max_length=64, verbose_name='Cost center / ref'),
        ),
    ]
