# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0011_alter_pcfreplenishment_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccounttransfer',
            name='voucher_no',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]