# Generated by Django 5.2.17 on 2026-09-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0014_transfer_approval_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccounttransfer',
            name='check_issued',
            field=models.DateField(blank=True, help_text='Check issue date (optional)', null=True),
        ),
        migrations.AddField(
            model_name='interaccounttransfer',
            name='check_no',
            field=models.CharField(blank=True, help_text='Check number for this transfer (optional)', max_length=32),
        ),
    ]
