# Generated by Django 5.2.17 on 2026-09-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0015_interaccounttransfer_check_issued_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaccounttransfer',
            name='check_issued',
        ),
        migrations.AlterField(
            model_name='interaccounttransfer',
            name='check_no',
            field=models.CharField(blank=True, help_text='Check number (optional)', max_length=32),
        ),
    ]
