# Generated by Django 5.2.17 on 2026-09-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0016_remove_interaccounttransfer_check_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaccounttransfer',
            name='purpose',
            field=models.CharField(max_length=500),
        ),
    ]
