# Generated by Django 5.2.17 on 2026-09-19 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0018_backfill_transfer_line_descriptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccounttransfer',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaccounttransfer',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaccounttransfer',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interaccounttransfer',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=16),
        ),
    ]
