# Generated by Django 5.2.17 on 2026-09-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0020_pcfreplenishment_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcfreplenishment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted')], default='draft', max_length=16),
        ),
    ]
