# Generated by Django 5.2.17 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0022_backfill_pc_account_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaccounttransfer',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Cost center / ref (e.g. OS — offsite, GEN-FUEL)', max_length=64),
        ),
    ]