# Generated by Django 5.2.17 on 2026-10-02 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0024_pcfreplenishment_cv'),
        ('foundation', '0013_userprofile_avatar_userprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashfund',
            name='payable_account',
            field=models.ForeignKey(blank=True, help_text='Payable credit account for PCF replenishment JEs (null = default 21100)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pcf_funds_payable', to='foundation.account'),
        ),
    ]
