# Generated by Django 5.2.17 on 2026-10-03 08:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0025_add_payable_account_to_pcfund'),
        ('posting', '0007_reversalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('side', models.CharField(choices=[('bank', 'Bank Side'), ('book', 'Book Side')], max_length=4)),
                ('category', models.CharField(choices=[('deposit_in_transit', 'Deposit in Transit'), ('bank_error_add', 'Bank Error (Add)'), ('outstanding_checks', 'Outstanding Checks'), ('bank_error_less', 'Bank Error (Less)'), ('bank_interest_earned', 'Bank Interest Earned'), ('book_error_add', 'Book Error (Add)'), ('bank_service_charge', 'Bank Service Charge'), ('nsf_daif_charges', 'NSF/DAIF Charges'), ('book_error_less', 'Book Error (Less)')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('adjusted', 'Adjusted')], default='unmatched', max_length=16)),
            ],
            options={
                'ordering': ['recon', 'side', 'category', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='reconciliation_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=8),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='adjusted_bank_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='adjusted_book_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=8),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='is_balances_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='period_end',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='period_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='pre_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='pre_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='unadjusted_bank_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='unadjusted_book_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddConstraint(
            model_name='bankreconciliation',
            constraint=models.UniqueConstraint(fields=('bank_account', 'period_start', 'period_end'), name='uniq_recon_bank_period'),
        ),
        migrations.AddField(
            model_name='bankreconline',
            name='adjustment_je',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_recon_lines', to='posting.journalentry'),
        ),
        migrations.AddField(
            model_name='bankreconline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankreconline',
            name='recon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cash.bankreconciliation'),
        ),
        migrations.AddField(
            model_name='bankreconline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
