# Generated by Django 5.2.17 on 2026-10-06 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0024_supplier_is_employee_advancereconciliation'),
        ('cash', '0027_backfill_recon_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcfreplenishment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcf_replenishments', to='ap.supplier'),
        ),
    ]
