# Generated by Django 5.2.17 on 2026-08-14 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('form_code', models.CharField(db_index=True, max_length=32)),
                ('year', models.PositiveIntegerField()),
                ('pattern', models.CharField(default='{YYYY}-{SEQ:05d}', max_length=64)),
                ('next_seq', models.PositiveBigIntegerField(default=1)),
                ('cost_center', models.CharField(blank=True, max_length=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequences', to='foundation.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['form_code', 'year'],
                'unique_together': {('company', 'form_code', 'year', 'cost_center')},
            },
        ),
    ]
