# Generated by Django 5.2.17 on 2026-08-14 08:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0001_initial'),
        ('posting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CONSOBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('batch_no', models.CharField(max_length=16, unique=True)),
                ('conso_date', models.DateField(db_index=True)),
                ('status', models.CharField(default='open', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-conso_date', '-batch_no'],
            },
        ),
        migrations.CreateModel(
            name='RFPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ap_number', models.CharField(max_length=16, unique=True)),
                ('last_ap', models.CharField(blank=True, max_length=16)),
                ('rfp_date', models.DateField(db_index=True)),
                ('particulars', models.CharField(max_length=500)),
                ('purpose', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('20000.00'), max_digits=18)),
                ('status', models.CharField(db_index=True, default='draft', max_length=24)),
                ('conso_line_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('approved_by_acctg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_by_cnr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_by_fin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('conso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfps', to='ap.consobatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfps', to='posting.journalentry')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfps', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rfp_date', '-ap_number'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceToEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('employee', 'Employee reimbursement'), ('officer', 'Officer advance'), ('salary_advance', 'Salary advance'), ('reimbursement', 'Reimbursement')], default='employee', max_length=24)),
                ('granted_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(default='granted', max_length=16)),
                ('liquidated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('liquidated_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rfp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='ap.rfpdocument')),
            ],
            options={
                'ordering': ['-granted_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('supplier_type', models.CharField(choices=[('depot', 'Depot'), ('equipment', 'Equipment'), ('service', 'Service'), ('govt', 'Government'), ('other', 'Other')], default='other', max_length=16)),
                ('tin', models.CharField(blank=True, max_length=32, verbose_name='TIN')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('contact_no', models.CharField(blank=True, max_length=32)),
                ('last_ap', models.CharField(blank=True, max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='foundation.segment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='rfpdocument',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfps', to='ap.supplier'),
        ),
        migrations.CreateModel(
            name='CheckVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cv_number', models.CharField(max_length=16, unique=True)),
                ('cv_date', models.DateField(db_index=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('withheld_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('check_no', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(default='created', max_length=16)),
                ('bank_account', models.ForeignKey(limit_choices_to={'code__startswith': '100'}, on_delete=django.db.models.deletion.PROTECT, related_name='cv', to='foundation.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cv', to='posting.journalentry')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rfp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cv', to='ap.rfpdocument')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cv', to='ap.supplier')),
            ],
            options={
                'ordering': ['-cv_date', '-cv_number'],
            },
        ),
        migrations.CreateModel(
            name='RFPLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfp_lines', to='foundation.account')),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ap.rfpdocument')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfp_lines', to='foundation.segment')),
            ],
            options={
                'ordering': ['rfp', 'line_no'],
                'unique_together': {('rfp', 'line_no')},
            },
        ),
    ]
