# Generated by Django 5.2.17 on 2026-08-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfpdocument',
            name='advance_amount',
        ),
        migrations.AddField(
            model_name='rfpline',
            name='side',
            field=models.CharField(choices=[('dr', 'Dr'), ('cr', 'Cr')], default='dr', max_length=2),
        ),
        migrations.AlterField(
            model_name='rfpdocument',
            name='particulars',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
