# Generated by Django 5.2.6 on 2026-09-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0002_rfp_manual_sides'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='attachments_required',
            field=models.BooleanField(default=False, verbose_name='Attachment Needed (BIR-COR, DTI/SEC, Business Permit)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Owner/Representative/President'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='position',
            field=models.CharField(blank=True, max_length=128, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
