# Generated by Django 5.2.17 on 2026-09-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0004_rfpdocument_rejected_at_rfpdocument_rejected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfpdocument',
            name='finance_notes',
            field=models.TextField(blank=True, help_text='Notes from Finance Head for Ellen/COO'),
        ),
        migrations.AddField(
            model_name='rfpdocument',
            name='revision_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
