# Generated by Django 5.2.6 on 2026-09-07 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0006_suppliercontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkvoucher',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkvoucher',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkvoucher',
            name='rejection_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checkvoucher',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
