# Generated by Django 5.2.17 on 2026-09-07 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0007_checkvoucher_rejected_at_checkvoucher_rejected_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('rfp', 'RFP'), ('cv', 'Check Voucher')], db_index=True, max_length=8)),
                ('doc_id', models.PositiveBigIntegerField(db_index=True)),
                ('action', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['doc_type', 'doc_id'], name='ap_actionlo_doc_typ_d2db1e_idx')],
            },
        ),
    ]
