# Generated by Django 5.2.17 on 2026-09-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0009_checkvoucher_approved_remove_signed_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfpline',
            name='cost_center',
            field=models.CharField(blank=True, max_length=64, verbose_name='Coscenter/ref'),
        ),
    ]
