# Generated by Django 5.2.17 on 2026-09-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0010_rfpline_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfpline',
            name='cost_center',
            field=models.CharField(blank=True, max_length=64, verbose_name='Cost Center/Ref'),
        ),
    ]
