# Generated by Django 5.2.6 on 2026-09-15 03:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0011_alter_rfpline_cost_center'),
        ('foundation', '0011_account_behavior_account_controllability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='doc_type',
            field=models.CharField(choices=[('rfp', 'RFP'), ('cv', 'Check Voucher'), ('po', 'Purchase Order')], db_index=True, max_length=8),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('po_number', models.CharField(max_length=16, unique=True)),
                ('po_date', models.DateField(db_index=True)),
                ('particulars', models.CharField(blank=True, max_length=500)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('contract_duration', models.CharField(blank=True, max_length=255)),
                ('ship_to_company', models.CharField(blank=True, max_length=255, verbose_name='Deliver to — Company')),
                ('ship_to_address', models.CharField(blank=True, max_length=255, verbose_name='Deliver to — Address')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Deliver to — Contact Person')),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='VAT')),
                ('other_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(db_index=True, default='prepared', max_length=24)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('finance_notes', models.TextField(blank=True, help_text='Notes from Finance Head for Ellen/COO')),
                ('revision_count', models.PositiveSmallIntegerField(default=0)),
                ('approved_by_acctg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_by_cnr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_by_fin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos', to='foundation.segment')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos', to='ap.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-po_date', '-po_number'],
            },
        ),
        migrations.AddField(
            model_name='rfpdocument',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfps', to='ap.purchaseorder'),
        ),
        migrations.CreateModel(
            name='POLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('pr_number', models.CharField(blank=True, max_length=32, verbose_name='PR No.')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='QTY')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='UNIT')),
                ('description', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ap.purchaseorder')),
            ],
            options={
                'ordering': ['po', 'line_no'],
                'unique_together': {('po', 'line_no')},
            },
        ),
    ]
