# Generated by Django 5.2.6 on 2026-09-15 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0012_alter_actionlog_doc_type_purchaseorder_and_more'),
        ('foundation', '0011_account_behavior_account_controllability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='foundation.account'),
        ),
    ]
