# Generated by Django 5.2.6 on 2026-09-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0013_poline_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='doc_type',
            field=models.CharField(choices=[('rfp', 'RFP'), ('cv', 'Check Voucher'), ('po', 'Purchase Order'), ('ar', 'Acknowledgment Receipt'), ('dep', 'Bank Deposit')], db_index=True, max_length=8),
        ),
    ]
