# Generated by Django 5.2.17 on 2026-09-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0016_alter_actionlog_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='doc_type',
            field=models.CharField(choices=[('rfp', 'RFP'), ('cv', 'Check Voucher'), ('po', 'Purchase Order'), ('ar', 'Acknowledgment Receipt'), ('dep', 'Bank Deposit'), ('transfer', 'Fund Transfer'), ('je', 'Journal Entry'), ('bill', 'Billing')], db_index=True, max_length=8),
        ),
    ]
