# Generated by Django 5.2.6 on 2026-10-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0019_supplier_approval_status_supplier_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_receipt_no',
            field=models.CharField(blank=True, max_length=32, verbose_name='DR No.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Received Date'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='receiving_report_no',
            field=models.CharField(blank=True, max_length=32, verbose_name='RR No.'),
        ),
        migrations.AddField(
            model_name='rfpdocument',
            name='supplier_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice Date'),
        ),
        migrations.AddField(
            model_name='rfpdocument',
            name='supplier_invoice_no',
            field=models.CharField(blank=True, max_length=32, verbose_name='Supplier Invoice No.'),
        ),
    ]
