# Generated by Django 5.2.6 on 2026-10-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0020_purchaseorder_delivery_receipt_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='attachment',
            field=models.FileField(blank=True, upload_to='po_supporting/'),
        ),
        migrations.AddField(
            model_name='rfpdocument',
            name='attachment',
            field=models.FileField(blank=True, upload_to='rfp_supporting/'),
        ),
    ]
