# Generated by Django 5.2.17 on 2026-10-06 05:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0023_alter_actionlog_doc_type'),
        ('posting', '0008_backfill_voucher_party_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_employee',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Employee (appears in Advances pickers)'),
        ),
        migrations.CreateModel(
            name='AdvanceReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('employee_name', models.CharField(db_index=True, max_length=255)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('gl_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('reviewed_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('memo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('locked', 'Locked')], db_index=True, default='draft', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('adjustment_je', models.ForeignKey(blank=True, help_text='Posted adjusting JE that books the variance into 12070.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_reconciliations', to='posting.journalentry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, help_text='Canonical employee (Supplier flagged is_employee).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance_reconciliations', to='ap.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', 'employee_name'],
                'indexes': [models.Index(fields=['employee_name', 'period_end'], name='ap_advancer_employe_a2e910_idx'), models.Index(fields=['status', 'period_end'], name='ap_advancer_status_fb4545_idx')],
            },
        ),
    ]
