# Generated by Django 5.2.17 on 2026-10-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0024_supplier_is_employee_advancereconciliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='doc_type',
            field=models.CharField(choices=[('rfp', 'RFP'), ('cv', 'Check Voucher'), ('po', 'Purchase Order'), ('ar', 'Acknowledgment Receipt'), ('dep', 'Bank Deposit'), ('transfer', 'Fund Transfer'), ('je', 'Journal Entry'), ('bill', 'Billing'), ('asset', 'Fixed Asset'), ('ssi', 'Special Sales Invoice'), ('adv', 'Advance Reconciliation')], db_index=True, max_length=8),
        ),
    ]
